export { FogmaIcon } from "./components/icon.js"
export { FogmaCanvas } from "./components/canvas/fogma-canvas.js"
export { CanvasNode } from "./components/canvas/canvas-node.js"
export { CanvasLabel } from "./components/canvas/canvas-label.js"
export { CanvasClickOverlay } from "./components/canvas/canvas-click-overlay.js"
export { FloatingControls } from "./components/canvas/floating-controls.js"
export { BackButton } from "./components/canvas/back-button.js"
export { GuideOverlay } from "./components/canvas/guide-overlay.js"
export { LazyIframe } from "./components/canvas/lazy-iframe.js"
export { useDraggableNode } from "./hooks/use-draggable-node.js"
export { FogmaSidebar } from "./components/sidebar/fogma-sidebar.js"
export type { FogmaSelection, SidebarSection, SidebarEntry } from "./components/sidebar/fogma-sidebar.js"
export { buildPageTree } from "./components/sidebar/page-tree.js"
export type { PageTreeNode } from "./components/sidebar/page-tree.js"
export { serializeSelection, parseSelection } from "./components/sidebar/selection-hash.js"
export { useIframePreview } from "./hooks/use-iframe-preview.js"
export { useIframeEditWiring } from "./hooks/use-iframe-edit-wiring.js"
export { useIframeSpacingWiring } from "./hooks/use-iframe-spacing-wiring.js"
export type { SpacingZoneTarget, SpacingSide } from "./hooks/use-iframe-spacing-wiring.js"
export { useIframeBlockDoubleClick } from "./hooks/use-iframe-block-dblclick.js"
export { ResponsiveFrameView, responsiveFrameStageDimensions } from "./components/canvas/responsive-frame-view.js"
export { EditPopover } from "./components/canvas/edit-popover.js"
export { SpacingPicker } from "./components/canvas/spacing-picker.js"
export { SpacingBodyMenu } from "./components/canvas/spacing-body-menu.js"
export { isTextElement, computeDomPath, PREVIEW_EDIT_CSS, PREVIEW_AGENT_CSS, PREVIEW_COMPOSE_CSS } from "./lib/edit-mode.js"
export { inspectElement, type InspectionResult, type AppliedToken } from "./lib/inspect-element.js"
export { resolvePaddingClass, resolveGapClass, extractMarginClasses, type ResolvedSpacingClass } from "./lib/spacing-classes.js"
export { InspectPanel } from "./components/inspect-panel.js"
